In [1]:
#numpy
import numpy as np

In [2]:
import numpy as np

print(np.__version__)

1.21.5


In [3]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
my_list = [1, 2, 3, 4]
my_array = np.array(my_list)
my_2darray = np.array([[1,2,3],[4,5,6]])

In [5]:
my_array

array([1, 2, 3, 4])

In [6]:
my_2darray

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
my_array[1]

2

In [8]:
my_array[0:2]

array([1, 2])

In [9]:
my_array > 3

array([False, False, False,  True])

In [10]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
my_array.shape #dizi boyutunu alma

(4,)

In [12]:
arr3=np.array([1,7,8,9,45])
arr3.shape

(5,)

In [13]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)


In [14]:
a,b,c

(array([1, 2, 3]),
 array([[1.5, 2. , 3. ],
        [4. , 5. , 6. ]]),
 array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]],
 
        [[3. , 2. , 1. ],
         [4. , 5. , 6. ]]]))

In [15]:
a

array([1, 2, 3])

In [16]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [17]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [18]:
np.append(a,5) #a dizisine 5 sayısını ekler

array([1, 2, 3, 5])

In [19]:
my_array

array([1, 2, 3, 4])

In [20]:
np.insert(my_array, 2, 8) #dizinin 2.elemanına 8 ekler

array([1, 2, 8, 3, 4])

In [21]:
np.delete(my_array,[1]) #dizinin 1. elemanını siler

array([1, 3, 4])

In [22]:
np.median(my_array) #medyanın alır

2.5

In [23]:
np.std(my_array)

1.118033988749895

In [24]:
np.zeros((3,4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
 np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [26]:
d = np.arange(10,25,5) 

In [27]:
d

array([10, 15, 20])

In [28]:
np.linspace(0,2,9) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [29]:
e = np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [30]:
f = np.eye(2) 
f

array([[1., 0.],
       [0., 1.]])

In [31]:
np.random.randint((47,68)) 

array([10, 30])

In [32]:
np.empty((3,2)) 

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [33]:
np.save('my_array', a)
a

array([1, 2, 3])

In [34]:
np.load('my_array.npy')

array([1, 2, 3])

In [35]:
np.int64

numpy.int64

In [36]:
a.shape

(3,)

In [37]:
len(a)

3

In [38]:
a.ndim 

1

In [39]:
my_array.ndim


1

In [40]:
c.ndim #dizi boyutlarnın sayısı

3

In [41]:
c.size


12

In [42]:
a.size

3

In [43]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [44]:
h = a.view() 
h


array([1, 2, 3])

In [45]:
np.copy(c)

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [46]:
c.sort() 
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[1. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [47]:
b[1,2]

6.0

In [48]:
a


array([1, 2, 3])

In [49]:
a[0:2]

array([1, 2])

In [50]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [51]:
b[0:2,1] 

array([2., 5.])

In [52]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [53]:
i=np.transpose(b)
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [54]:
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [55]:
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [56]:
b.reshape(3,-2)

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [57]:
Z = np.zeros(10)
Z[1] = 1
print(Z)


[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


In [58]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [59]:
Z = np.arange(50) #tersine çevirme 
Z = Z[::-1]
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [60]:
Z = np.arange(4).reshape(2,2)
print(Z)


[[0 1]
 [2 3]]
